#pragma once
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include <functional>
#include "Core/Application.h"
#include "System/Time.h"
#include "Objects/GameObject.h"
#include "Objects/Camera/Camera.h"
#include "imgui.h"
#include "OpenGL/OpenGLInput.h"
#include "EntryPoint.h"
